### ISSUE TITLE
Error di Blade replacer

### ISSUE THREAD

**Issue by zhev89** [AdBank/Blade-Blocker#16]
I have, installed both extensions in chrome, but blade adblocker still asks to install blade crypto, the problem is I have installed both of them and still asked to download. My screenshot is included.
![Screenshot_8](https://user-images.githubusercontent.com/36322312/99324714-d1d95080-28af-11eb-86f2-ff0fc37f663a.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/36322312/99324717-d3a31400-28af-11eb-93ba-fd966c1f33ef.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/36322312/99324721-d43baa80-28af-11eb-95b8-437e2671999d.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/36322312/99324724-d43baa80-28af-11eb-9a53-b4c8ffcbe7e8.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/36322312/99324726-d4d44100-28af-11eb-886f-6e0937d6027f.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/36322312/99324727-d56cd780-28af-11eb-968c-c9d8a3bbe530.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/36322312/99324728-d6056e00-28af-11eb-8726-cb1d568eb5f3.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/36322312/99324730-d69e0480-28af-11eb-96e0-14200c5716f7.jpg)

**Comment by conorwatt1** [comment]
The 'download now' section intentionally left like that.

Also for the other screenshots, those are not real "errors". The extension was built with multiple browsers in mind, you are only seeing that output because for chrome our replacer is not in the store so the user has to installs it in dev/test mode

Thanks!

**Comment by zhev89** [comment]
thanks for your explanation
